Repository eth-cscs/alps-uenv, pull requests merged in 2024-06, with the labels that each got.

#99 Document how to use uenvs as upstream Spack instances
  docs/uenv-compilation-spack.md
  mkdocs.yml
Labels: documentation

#83 Add VASP recipe for GH200
  config.yaml
  docs/uenv-vasp.md
  mkdocs.yml
  recipes/vasp/v6.4.2/gh200/compilers.yaml
  recipes/vasp/v6.4.2/gh200/config.yaml
  recipes/vasp/v6.4.2/gh200/environments.yaml
  recipes/vasp/v6.4.2/gh200/modules.yaml
  recipes/vasp/v6.4.2/gh200/pre-install
  recipes/vasp/v6.4.2/gh200/repo/packages/libxc/0001-Bugfix-avoid-implicit-pointer-cast-to-make-libxc-com.patch
  recipes/vasp/v6.4.2/gh200/repo/packages/libxc/0002-Mark-xc_erfcx-a-GPU_FUNCTION.patch
  recipes/vasp/v6.4.2/gh200/repo/packages/libxc/nvhpc-configure.patch
  recipes/vasp/v6.4.2/gh200/repo/packages/libxc/nvhpc-libtool.patch
  recipes/vasp/v6.4.2/gh200/repo/packages/libxc/package.py
  recipes/vasp/v6.4.2/gh200/repo/packages/nvpl-blas/package.py
  recipes/vasp/v6.4.2/gh200/repo/packages/nvpl-lapack/package.py
  recipes/vasp/v6.4.2/gh200/repo/packages/vasp/mpix_cuda.patch
  recipes/vasp/v6.4.2/gh200/repo/packages/vasp/package.py
  stack-build
Labels: vasp, app

#92 qe7.3.1 for gh200
  config.yaml
  docs/uenv-linaro-forge.md
  docs/uenv-qe.md
  mkdocs.yml
  recipes/quantumespresso/v7.3.1/gh200/compilers.yaml
  recipes/quantumespresso/v7.3.1/gh200/config.yaml
  recipes/quantumespresso/v7.3.1/gh200/environments.yaml
  recipes/quantumespresso/v7.3.1/gh200/modules.yaml
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/libxc/0001-Bugfix-avoid-implicit-pointer-cast-to-make-libxc-com.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/libxc/0002-Mark-xc_erfcx-a-GPU_FUNCTION.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/libxc/nvhpc-configure.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/libxc/nvhpc-libtool.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/libxc/package.py
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/configure_aocc.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/dspev_drv_elpa.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/fj-fox.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/fj-intent.6.4.1.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/fj.6.5.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/fj.6.6.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/gipaw-eccee44.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/nvhpc.patch
  recipes/quantumespresso/v7.3.1/gh200/repo/packages/quantum-espresso/package.py
Labels: app, qe
